config/routes.rb
Rails.application.routes.draw do

  root 'punch_cards#index'
  resource :punch_card

end

app/models/punch.rb
class Punch < ActiveRecord::Base
  def punch_time
    return 0 if punch_out.nil?
    punch_out - punch_in
  end

  def working?
    punch_in && !punch_out
  end

  def punch
    if working? then
      self.punch_out = Time.now
    else
      self.punch_in = Time.now
    end
  end

  def punch_in= t
    super t unless working?
    super t if punch_in == nil
  end

  def punch_out= t
    super t if working?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/punch_cards_controller.rb
class PunchCardsController < ApplicationController

  def index
    @punches = Punch.all.order(:punch_in).reverse_order
  end

  def new
    @punch = Punch.create(punch_in: Time.now())
    flash[:success] = "Punched In Sucessfully"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timeclock" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">
            <%= image_tag 'RazorBuzz_Icon.png', class: "logo" %>
            Razor Timeclock
          </a>

          <div class="container nav-collapse">
            <ul class="nav tall-nav">
              <li><%= link_to "Punch Clock"%></li>
              <li><%= link_to "Timecard"%></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>

          <% flash.each do |key, value| %>
              <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>

          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Razor USA LLC 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/punch_cards/index.html.erb
<%= link_to new_punch_card_path do%>
    <button type="button" class="btn btn-default">Punch In <span class="icon-time"></span></button>
<% end %>

<h4>
Time Record
</h4>

<table class="table table-striped table-hover">
  <thead>
    <tr>
        <td>Punch In</td>
        <td>Punch Out</td>
        <td>Time Worked</td>
    </tr>
  </thead>
  <tbody>

  <% @punches.each do |punch| %>
  <tr id="<%=punch.id%>">
    <td><%= punch.punch_in%></td>
    <td><%= punch.punch_out%></td>
    <td><%= Time.at(punch.punch_time).gmtime.strftime('%R')%></td>
  </tr>
  <% end %>
  </tbody>
  </table>

app/views/punch_cards/new.html.erb
new punch